services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false
    bind:
      $bundleConfig: "%huh_advanced_member%"

  HeimrichHannot\AdvancedMemberBundle\:
    resource: "../src/{Command,DataContainer,EventListener}/*"

  HeimrichHannot\AdvancedMemberBundle\DataContainer\MemberContainer:
    public: true

  HeimrichHannot\AdvancedMemberBundle\DataContainer\MemberGroupContainer:
    public: true